### PR TITLE
Convert to async_forward_entry_setups

### LINKED ISSUE #54: Detected that custom integration 'hildebrand_glow_ihd' calls async_forward_entry_setup for integration
2024-07-05 12:31:43.268 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hildebrand_glow_ihd' calls async_forward_entry_setup for integration, hildebrand_glow_ihd with title: and entry_id: 755282d51d988efe6fe21d74175c7a4b, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/hildebrand_glow_ihd/__init__.py, line 34: hass.async_create_task(, please create a bug report at https://github.com/megakid/ha_hildebrand_glow_ihd_mqtt/issues

### PR DESCRIPTION
**Pull request by andrew-codechimp**
Fixes #54

### CODE REVIEW

**Review by ProximusAl — APPROVED** [review]
Tested locally, works great for me.

**Review by Blackduke77 — APPROVED** [review]
Tested and works for me and resolves the error

**Review by Blackduke77 — APPROVED** [review]

**Review by mccaffm — APPROVED** [review]
look code to me, but since i dont have write ?

**Comment by ProximusAl** [comment]
> look good to me, but since i dont have write ? Guess we need to wait for @ProximusAl

Nothing to do with me……We need @megakid to do a release based on the pull.

**Comment by mccaffm** [comment]
> > look good to me, but since i dont have write ? Guess we need to wait for @ProximusAl
> 
> Nothing to do with me……We need @megakid to do a release based on the pull.

I knew that :) - apologies @ProximusAl , thanks @megakid

**Comment by megakid** [comment]
Should be released now in v1.7.0. Thanks for all the contributions!

**Pull request merged**
