### PR TITLE
Added state_class 'TOTAL' to todays cost sensors

### PR DESCRIPTION
**Pull request by vladimir-babichev**
This PR addresses #35 by adding `state_class` `SensorStateClass.TOTAL` to `Smart Meter Electricity: Cost (Today)` and `Smart Meter Gas: Cost (Today)` sensors.

### CODE REVIEW

**Review by megakid — APPROVED** [review]
Thanks 🙏

**Comment by Excentyl** [comment]
Hi, I've had some issues with the total cost in the energy dashboard.

Unfortunately, I don't think the 'TOTAL' state class is the correct thing to use, unless a 'last_reset' attribute is added. Every day, the sensor resets to 0 (this is because the calculation uses the daily import) and so at the start of every day, the energy dashboard is taking away the cost from the previous day.

For example, if you use £10.00 on Monday and then £8.00 on Tuesday, the energy dashboard will show a cost of -£2.00 on Tuesday.

It looks to me that 'TOTAL_INCREASING' is correct state class to use, but I note that it was changed away from 'TOTAL_INCREASING' in version 1.6.1. Was something breaking when it was set to 'TOTAL_INCREASING'?

**Comment by sourbrambles** [comment]
> Hi, I've had some issues with the total cost in the energy dashboard.
> 
> Unfortunately, I don't think the 'TOTAL' state class is the correct thing to use, unless a 'last_reset' attribute is added. Every day, the sensor resets to 0 (this is because the calculation uses the daily import) and so at the start of every day, the energy dashboard is taking away the cost from the previous day.
> 
> For example, if you use £10.00 on Monday and then £8.00 on Tuesday, the energy dashboard will show a cost of -£2.00 on Tuesday.
> 
> It looks to me that 'TOTAL_INCREASING' is correct state class to use, but I note that it was changed away from 'TOTAL_INCREASING' in version 1.6.1. Was something breaking when it was set to 'TOTAL_INCREASING'?

You might want to log this as an issue, I have the same problem with negative values. Happy to log it but your description covers it.

**Comment by sourbrambles** [comment]
@vladimir-babichev I find the explanation on the Long-term Statistics confusing but I agree it looks like `TOTAL_INCREASING` would be the option. However from a quick parse of this [https://github.com/home-assistant/core/issues/88457](url) it sounds like the HA core developers would expect `total` & `last_rest` to be combined. It looks like the core development team don't see daily cost as the appropriate method for monetary calculations. There might be other info in that thread, I just had a quick skim

**Comment by megakid** [comment]
Happy to accept a working PR here but since these values are not accurate for me (I have a dual tariff and my IHD reports the wrong cost). 

As mentioned above, I removed the previous state_class because of the warning logs but would reinstate them if we can avoid them with another setting.

**Comment by cmatte** [comment]
I wanted to also flag this does calculate costs wrong for dynamic rates tariffs like Agile Octopus, where rates change every half an hour - is there a working or workaround solution for those?

**Comment by yashijoe** [comment]
Hello guys, this is my templete sensor:

`- sensor:
    - name: "Consumi bolletta"
      unique_id: 'sensor.consumi_bolletta'
      unit_of_measurement: "€"
      device_class: "monetary"
      state_class: "total"
      attributes:
        last_reset: "{{ today_at('23:59') }}"
      icon: mdi:cash
      # costo materia energia meno sconto del 30% a kwh: 0.6402 * 0.7
      # commercializzazione al mese: 7.471517
      # media dispacciamento + sbilanciamento a kwh: 0.01691
      # quota fissa al mese: 1.72
      # quota potenza impegnato al mese a Kw (8): 1.71*8
      # quota energia a kwh: 0.00848
      # quota energia -meccanismi perequativi- a kwh: 0.00095
      # Asos+Arim a kwh: 0.030263
      # accisa su materia energia a kwh: 0.0227
      # IVA al 10% sul totale: 1.1
      state: "{{ ((
                 (states('sensor.energia_giornaliera_f1') |float(0) + states('sensor.energia_giornaliera_f2') |float(0)) * 0.6402 * 0.7 +
                 7.471517 / states('sensor.days_in_current_month') |float(0) +
                 (states('sensor.energia_giornaliera_f1') |float(0) + states('sensor.energia_giornaliera_f2') |float(0) + states('sensor.energia_giornaliera_f3') |float(0)) * 0.01691 +
                 1.72 / states('sensor.days_in_current_month') |float(0) +
                 1.71*8 / states('sensor.days_in_current_month') |float(0) +
                 (states('sensor.energia_giornaliera_f1') |float(0) + states('sensor.energia_giornaliera_f2') |float(0) + states('sensor.energia_giornaliera_f3') |float(0)) * 0.00848 +
                 (states('sensor.energia_giornaliera_f1') |float(0) + states('sensor.energia_giornaliera_f2') |float(0) + states('sensor.energia_giornaliera_f3') |float(0)) * 0.00095 +
                 (states('sensor.energia_giornaliera_f1') |float(0) + states('sensor.energia_giornaliera_f2') |float(0) + states('sensor.energia_giornaliera_f3') |float(0)) * 0.030263 +
                 (states('sensor.energia_giornaliera_f1') |float(0) + states('sensor.energia_giornaliera_f2') |float(0) + states('sensor.energia_giornaliera_f3') |float(0)) * 0.0227) *
                 1.1) |round(2)
              }}"`

The state of the sensor reports 1.2 as value
While the Energy board reports 0.28

Where I've done it wrong?
Thank you in avance

**Pull request merged**
