### PR TITLE
Add last_reset attribute to daily cost sensors for correct Energy Dashboard costs

### PR DESCRIPTION
**Pull request by jeverley**
This introduces logic to correctly populate the _last_reset_ attribute of the monetary total sensors for gas and electicity.

Specifically this aims to address the issue raised in https://github.com/megakid/ha_hildebrand_glow_ihd_mqtt/issues/57

### CODE REVIEW

**Comment by Blackduke77** [comment]
I have just updated my install with this file and am not seeing the attribute on my totals, I will leave it in place and see if they appear tomorrow!

**Comment by Blackduke77** [comment]
Hi yes, if I look at states in developer tools, I see it as below, but I was looking at the entity and expecting to see it, which it isn't 

image
image

**Review by megakid — APPROVED** [review]

**Comment by megakid** [comment]
👍 thanks

**Comment by Blackduke77** [comment]
image
image

Looks like you are onto something.

**Comment by Blackduke77** [comment]
they are current

image

**Comment by jeverley** [comment]
Thanks for confirming, I think the current code should work for you then (as your meter is respecting DST).

I'll submit a PR tomorrow allowing users to configure an override - looks like it can be common with some suppliers: https://forums.moneysavingexpert.com/discussion/6452051/british-gas-electric-driver-ev-tariff-hours-gmt-vs-bst

**Comment by Blackduke77** [comment]
Happy to test, apart from basic functionality, is there anything else to test, do you want me to reset integration and reset it back up

**Comment by jeverley** [comment]
Thanks @Blackduke77, it'd be good to test the following scenarios:

- Update and make no config changes
  - Verify that last_reset populates for both electricity and gas using local midnight (23:00 UTC)
- Choose Configure on your existing instance
  - Verify that the topic prefix and device ID match what you configured previously
  - Verify that the time zones default to the correct local time zone and that you can make and save a config change 
  - Verify that the changes persist if you re-open the configure option
- Set up a new instance of the integration

One thing I do notice is that the only way to make config changes take effect is to restart home assistant (this is also the case with the existing release).

I might have a look at making it reloadable similar to other integrations, though I'm off on holiday for the next week so it'll need to wait :)

**Pull request merged**
